# Generated by Django 5.0 on 2024-01-08 09:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sorryquiz', '0002_userresponse'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userresponse',
            old_name='choice',
            new_name='selected_choice',
        ),
    ]
